apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x1p3oy5jf-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x1p3oy5jf-python 
  name: x1p3oy5jf-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: x1p3oy5jf-python 
