apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: x1p3oy5jf-python-gitops
  description: This is GitOps manifest for x1p3oy5jf-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=x1p3oy5jf-python
    backstage.io/kubernetes-id: x1p3oy5jf-python 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/x1p3oy5jf-python-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:x1p3oy5jf-python
